### ISSUE TITLE
Switch from Yarn wrapper to vm.selectFork

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/sweet-caramel#1214]
Recent versions of Foundry introduced the `vm.SelectFork` cheatcode, which lets us select an RPC endpoint and fork block directly from the tests. We can now remove the Yarn wrapper script and hardhat task we're using to run Forge fork tests.

**Comment by RedVeil** [comment]
@ecmendenhall how do we use env variables in foundry

**Comment by ecmendenhall** [comment]
Here's the best pattern I've found for using env variables + selectFork in forge: https://twitter.com/msolomon44/status/1564742781129502722

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1364

**Comment by RedVeil** [comment]
@Amirjab21 Lets Discuss the env before merging

**Comment by Amirjab21** [comment]
It's possible, I'm trying to get more info on how they use the dotenv package but it's a bit confusing to me atm. Plus the change might be quite large as this is the response from their team on one of the issues:

"the dotenv dependency we're using has its limitations, this is raised from time to time.

Not a priority to get this fixed at this point, since this would require writing an entirely new parser."

**Comment by Amirjab21** [comment]
potential solution:

Write script to copy .env file from root to hardhat folder.
