### ISSUE TITLE
add addAuthorizedContract from RewardsEscrow in vault factory

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#1228]
When a staking contract is created, it should be registered with the RewardsEscrow contract e.g. `rewardsEscrow.addAuthorizedContract(stakingAddress)`

on VaultsV1Controller we should update authorized in RewardsEscrow when calling "setVaultStaking"

**Comment by RedVeil** [comment]
@anthonymartin RewardsEscrow is ownable and used across vault and non-vault contracts. We would need to transfer ownership to the VaultsV1Controller in order to fullfill this ticket. It might make more sense to create a foundry script here that calls the controller to create a new vault and in that creation script authorizes the staking contract aswell. 
Alternatively we could deploy a second RewardsEscrow contract just for Vaults. This one could than be owned by VaultsV1Controller.

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/1243
