### ISSUE TITLE
docify build is failing

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#871]
When merging to develop the docify docgen build step is failing: https://github.com/popcorndao/sweet-caramel/runs/6995395725?check_suite_focus=true

![Screen Shot 2022-06-21 at 8.45.40 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/e0415ea6-21fc-4e71-adc3-50e25ef8da44)

**Comment by Amirjab21** [comment]
2 possible solutions:

1) We add solc-0.8.13 --> this compiler does not need the override function to be explicitly set on addContracts(). The problem with this solution is that it doesn't work on node v12 because the solc-0.8.13 package is nto compatible with node version 12.

2) add override to the addContracts() function so that the 0.8.0 compiler can compile ContractRegistry and therefore Docgen uses 0.8.0 and it all works.

2) add override to the addContract function

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/872

Went for adding override to the addContract function
